name: portfolio
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  url_strategy: ^0.2.0
  flutter_svg: ^2.0.10+1
  universal_html: ^2.2.4
  blurrycontainer: ^2.1.0
  cloud_firestore: ^5.0.0
  scrollable_positioned_list: ^0.3.8
  sticky_headers: ^0.3.0+2
  firebase_storage: ^12.0.0
  flutter_cache_manager: ^3.3.2
  pdf_render: ^1.4.8
  pdfx: ^2.6.0
  path_provider: ^2.1.3
  flutter_full_pdf_viewer_null_safe: ^1.0.0
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_pdfviewer: ^24.2.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/angle-right-solid.svg
    - assets/images/angle-left-solid.svg
    - assets/images/arrow-right-solid.svg
    - assets/images/link-solid.svg
    - assets/images/github.svg
    - assets/images/linkedin.svg
    - assets/images/404.svg

  fonts:
    - family: SFProMedium
      fonts:
        - asset: assets/fonts/SF-Pro-Medium.otf

    - family: SFProBold
      fonts:
        - asset: assets/fonts/SF-Pro-Heavy.otf

    - family: SFProRegular
      fonts:
        - asset: assets/fonts/SF-Pro-Regular.otf
